name = "bin"
main = "dist/index.js"

account_id = "d5ccf1d783709bbdc23fc29786f38736"
workers_dev = true
kv_namespaces = [
  { binding = "BIN_BIN", id="05129c34c7f84cfb8ad000432c8f4610" },
  { binding = "URL_BIN", id="53a3fa54cb624860af9d366c8b09a8c7" }
]
compatibility_date = "2022-03-22"

[build]
command = "npm run build"